// Estilos da interface do funcionário (mobile / "telefone").
import { COLORS } from "./colors.js";

const mobStyles = {
  page: { background: COLORS.bg, minHeight: "700px", display: "flex", justifyContent: "center", padding: "24px 16px", fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif", color: COLORS.text },
  // QA (achado do Iago, 3ª volta — "só a página Horas não tem o fundo
  // branco atrás"): era o contrário do que parecia — Horas (ecrã mais
  // novo) não embrulha tudo numa caixa branca sólida, só deixa o fundo
  // claro da própria casca (COLORS.bg/page, #F3F6F4 — já não é #FFFFFF
  // puro) aparecer por trás dos cartões brancos individuais. Estas telas
  // mais antigas faziam o oposto: uma única "caixa" branca (`background`/
  // `border`/`borderRadius` abaixo) por cima de tudo, escondendo esse
  // tom. Removidos os três pra ficar igual a Horas em todas — o Iago
  // pediu exatamente este tom (não branco puro) "fora da caixa" em
  // qualquer tela.
  phone: { width: "100%", maxWidth: 400, padding: "18px 18px 22px", position: "relative" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
  phoneProductRow: { display: "flex", justifyContent: "center", marginBottom: 16, paddingBottom: 16, borderBottom: `1px solid ${COLORS.border}` },
  // Varredura de QA pós-Etapa 4: 36px ficava abaixo do alvo de toque mínimo
  // em mobile (secção 9 do documento) — acordado com o Toni em 40px.
  // Lote 4, 4.4 (achado da Marta): "unificar" com o botão Início de
  // Horas (44×44, MobileHeader.jsx) — os dois passam a usar o alvo de
  // toque mobile do padrão novo por dispositivo (48×48).
  homeIcon: { width: 48, height: 48, borderRadius: "50%", background: COLORS.bg, border: "none", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  switchLink: { fontSize: 11, color: COLORS.textSoft, textDecoration: "underline", background: "none", border: "none", cursor: "pointer", display: "block", marginTop: 6 },
  greeting: { fontSize: 15, fontWeight: 600 },
  menuList: { display: "flex", flexDirection: "column", gap: 12, marginTop: 24 },
  menuButton: { position: "relative", padding: "18px", borderRadius: 14, border: `1px solid ${COLORS.border}`, background: COLORS.bg, fontSize: 15, fontWeight: 700, letterSpacing: "0.4px", color: COLORS.text, cursor: "pointer", transition: "border-color 0.15s" },
  menuBadge: { position: "absolute", top: 10, right: 12, background: COLORS.extra, color: "#fff", fontSize: 11, fontWeight: 700, borderRadius: 20, padding: "2px 7px" },
  sairRow: { textAlign: "center", marginTop: 28 },
  sairLink: { fontSize: 13, color: COLORS.textSoft, textDecoration: "underline", background: "none", border: "none", cursor: "pointer" },

  title: { textAlign: "center", fontFamily: "'Poppins', sans-serif", fontSize: 21, fontWeight: 600, margin: "6px 0 14px", letterSpacing: "0.1px" },
  periodRow: { display: "flex", alignItems: "center", gap: 8 },
  periodNav: { width: 28, height: 28, borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.bg, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.textSoft, flexShrink: 0 },
  weekLabel: { fontSize: 22, color: COLORS.text, fontWeight: 700, letterSpacing: "0.1px" },
  weekNav: { display: "flex", alignItems: "center", justifyContent: "center", gap: 10, marginBottom: 16 },

  horasTop: { marginBottom: 10 },
  subtitle: { fontSize: 11.5, fontWeight: 700, color: COLORS.textSoft, textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 4 },
  periodMetaRow: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 6, marginTop: 6 },
  currentWeekBadge: { display: "inline-block", fontSize: 11, fontWeight: 700, color: COLORS.primaryDark, background: COLORS.primaryTint, borderRadius: 20, padding: "3px 9px" },
  boundaryBadge: { display: "inline-block", fontSize: 11, fontWeight: 600, color: COLORS.extra, background: COLORS.extraTint, borderRadius: 6, padding: "3px 8px" },
  dayGrid: { display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 8 },
  dayChip: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2, padding: "10px 4px", borderRadius: 12, borderStyle: "solid", cursor: "pointer", position: "relative", flex: "1 1 76px", maxWidth: 96 },
  dayIcon: { width: 18, height: 18, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", position: "absolute", top: 6, right: 6 },
  dayAbbr: { fontSize: 13, fontWeight: 600, marginTop: 6 },
  dayDate: { fontSize: 11, color: COLORS.textSoft },
  dayHours: { fontSize: 11, color: COLORS.textSoft },
  panel: { marginTop: 14 },
  panelTitle: { fontSize: 15, fontWeight: 600, margin: "0 0 12px" },
  searchWrap: { display: "flex", alignItems: "center", gap: 8, background: COLORS.bg, border: `1px solid ${COLORS.border}`, borderRadius: 10, padding: "10px 12px", marginBottom: 12 },
  searchInput: { border: "none", outline: "none", background: "transparent", fontSize: 14, width: "100%", color: COLORS.text },
  resultsBox: { marginTop: -4, marginBottom: 8, border: `1px solid ${COLORS.border}`, borderRadius: 10, overflow: "hidden" },
  resultRow: { display: "flex", justifyContent: "space-between", alignItems: "center", width: "100%", padding: "10px 12px", background: COLORS.surface, border: "none", borderBottom: `1px solid ${COLORS.border}`, fontSize: 14, cursor: "pointer", color: COLORS.text, textAlign: "left" },
  resultMeta: { display: "flex", alignItems: "center", gap: 8 },
  selectedHeader: { fontSize: 12, fontWeight: 600, color: COLORS.textSoft, marginTop: 4, marginBottom: 8 },
  emptyState: { fontSize: 13, color: COLORS.textSoft, padding: "14px 0", textAlign: "center", border: `1px dashed ${COLORS.border}`, borderRadius: 10 },
  selectedList: { display: "flex", flexDirection: "column", gap: 8 },
  selectedRow: { display: "flex", justifyContent: "space-between", alignItems: "center", background: COLORS.bg, borderRadius: 10, padding: "10px 12px", gap: 10 },
  selectedName: { fontSize: 14, fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  selectedDuration: { fontSize: 12, color: COLORS.textSoft, marginTop: 2 },
  extraBadge: { color: COLORS.extra, fontWeight: 600 },
  extraButton: { width: 30, height: 30, borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.surface, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.textSoft, flexShrink: 0 },
  removeButton: { width: 30, height: 30, borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.surface, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.textSoft, flexShrink: 0 },
  finalizeDayButton: { width: "100%", marginTop: 16, padding: "12px", borderRadius: 10, border: `1px solid ${COLORS.primary}`, background: COLORS.primaryTint, color: COLORS.primaryDark, fontSize: 14, fontWeight: 600, cursor: "pointer", letterSpacing: "0.1px" },
  footer: { marginTop: 20, paddingTop: 16, borderTop: `1px solid ${COLORS.border}`, display: "flex", justifyContent: "space-between", alignItems: "center" },
  footerLabel: { fontSize: 11, color: COLORS.textSoft, fontWeight: 500 },
  footerValue: { fontSize: 20, fontWeight: 600, marginTop: 2 },
  finalizeWeekButton: { display: "flex", alignItems: "center", padding: "12px 18px", borderRadius: 10, border: "none", background: COLORS.primary, color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer", letterSpacing: "0.1px", boxShadow: "0 2px 6px rgba(20,63,53,0.24)" },
  toast: { position: "absolute", bottom: 90, left: "50%", transform: "translateX(-50%)", background: COLORS.primaryDark, color: "#fff", padding: "8px 16px", borderRadius: 20, fontSize: 13, fontWeight: 500 },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(22, 33, 29, 0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50, padding: 20 },
  modalCard: { background: COLORS.surface, borderRadius: 16, padding: 20, width: "100%", maxWidth: 320 },
  modalTitle: { fontSize: 16, fontWeight: 600, marginBottom: 6 },
  modalQuestion: { fontSize: 13, color: COLORS.textSoft, marginBottom: 16 },
  stepperRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 20, marginBottom: 8 },
  stepperButton: { width: 40, height: 40, borderRadius: "50%", border: `1px solid ${COLORS.border}`, background: COLORS.bg, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.text },
  stepperValue: { fontSize: 20, fontWeight: 600, minWidth: 70, textAlign: "center" },
  modalHint: { fontSize: 12, color: COLORS.textSoft, textAlign: "center", marginBottom: 18 },
  modalActions: { display: "flex", gap: 10 },
  modalCancel: { flex: 1, padding: "11px", borderRadius: 10, border: `1px solid ${COLORS.border}`, background: COLORS.surface, fontSize: 14, fontWeight: 600, cursor: "pointer", color: COLORS.text },
  modalConfirm: { flex: 1, padding: "11px", borderRadius: 10, border: "none", background: COLORS.primary, color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer", boxShadow: "0 2px 6px rgba(20,63,53,0.22)" },
  modalConfirmDanger: { flex: 1, padding: "11px", borderRadius: 10, border: "none", background: COLORS.extra, color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer" },
  lockedBanner: { position: "fixed", bottom: 20, left: "50%", transform: "translateX(-50%)", display: "flex", gap: 10, alignItems: "flex-start", background: COLORS.primaryTint, border: `1px solid ${COLORS.primary}`, borderRadius: 12, padding: "12px 14px", maxWidth: 360, zIndex: 40 },
  lockedBannerTitle: { fontSize: 13, fontWeight: 600, color: COLORS.primaryDark },
  lockedBannerBody: { fontSize: 12, color: COLORS.primaryDark, marginTop: 2 },

  dayList: { display: "flex", flexDirection: "column", gap: 10 },
  dayCard: { border: `1px solid ${COLORS.border}`, borderRadius: 14, overflow: "hidden" },
  agendaDayHeader: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 16px", background: COLORS.surface, border: "none", cursor: "pointer" },
  dayHeaderLeft: { display: "flex", alignItems: "center", gap: 8 },
  dayAbbrBold: { fontSize: 15, fontWeight: 700 },
  todayDot: { width: 6, height: 6, borderRadius: "50%", background: COLORS.primary },
  dayTotalPill: { fontSize: 12, fontWeight: 700, color: COLORS.primaryDark, background: COLORS.primaryTint, borderRadius: 20, padding: "4px 10px", minWidth: 20, textAlign: "center" },
  agendaDayBody: { padding: "12px 16px 16px", background: COLORS.bg },
  emptyDay: { fontSize: 13, color: COLORS.textSoft, padding: "8px 0" },
  chipList: { display: "flex", flexDirection: "column", gap: 8 },
  chip: { border: `1px solid ${COLORS.primary}`, borderRadius: 10, padding: "8px 10px", background: COLORS.primaryTint, display: "flex", alignItems: "flex-start" },
  chipTopRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, width: "100%" },
  chipName: { fontSize: 13, fontWeight: 600, color: COLORS.primaryDark },
  chipMeta: { fontSize: 11, color: COLORS.textSoft, marginTop: 1 },
  movedTag: { color: COLORS.extra, fontWeight: 600 },
  moveButton: { display: "flex", alignItems: "center", padding: "6px 10px", borderRadius: 8, border: "none", background: COLORS.primary, color: "#fff", fontSize: 11, fontWeight: 600, cursor: "pointer", whiteSpace: "nowrap" },
  iconButton: { width: 26, height: 26, borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.surface, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.textSoft, flexShrink: 0 },
  pickerBox: { width: "100%" },
  pickerHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 },
  pickerLabel: { fontSize: 11, color: COLORS.textSoft, marginTop: 2 },
  pickerClose: { width: 22, height: 22, borderRadius: "50%", border: "none", background: "rgba(31,111,92,0.12)", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.primaryDark, flexShrink: 0 },
  pickerGrid: { display: "flex", flexWrap: "wrap", gap: 6 },
  pickerDay: { padding: "7px 10px", borderRadius: 8, border: `1px solid ${COLORS.primary}`, background: COLORS.surface, fontSize: 12, fontWeight: 600, color: COLORS.primaryDark, cursor: "pointer" },
  descRowStatic: { width: "100%", marginTop: 8, paddingTop: 8, borderTop: "1px solid rgba(31,111,92,0.15)" },
  descText: { fontSize: 12, color: COLORS.primaryDark, lineHeight: 1.4 },
  footNote: { fontSize: 11, color: COLORS.textSoft, textAlign: "center", marginTop: 16, lineHeight: 1.5 },

  clientList: { display: "flex", flexDirection: "column", gap: 10 },
  clientCard: { border: `1px solid ${COLORS.border}`, borderRadius: 14, overflow: "hidden" },
  clientHeader: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "12px 14px", background: COLORS.surface, border: "none", cursor: "pointer", gap: 10 },
  clientHeaderLeft: { display: "flex", alignItems: "center", gap: 10, minWidth: 0 },
  iconCircle: { width: 36, height: 36, borderRadius: "50%", background: COLORS.primaryTint, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  clientName: { fontSize: 14, fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: 220 },
  clientSub: { fontSize: 11, color: COLORS.textSoft, marginTop: 1 },
  clientBody: { padding: "12px 14px 16px", background: COLORS.bg, display: "flex", flexDirection: "column", gap: 12 },
  detailBlock: {},
  detailLabel: { fontSize: 11, fontWeight: 700, color: COLORS.textSoft, textTransform: "uppercase", letterSpacing: "0.4px", marginBottom: 4 },
  detailText: { fontSize: 13, color: COLORS.text, lineHeight: 1.4 },
  addressRow: { display: "flex", flexDirection: "column", gap: 4 },
  mapLink: { display: "flex", alignItems: "center", fontSize: 12, fontWeight: 600, color: COLORS.primary },
  noDetails: { fontSize: 12, color: COLORS.textSoft, fontStyle: "italic" },

  avisosForm: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 18 },
  avisosFieldsRow: { display: "flex", gap: 10 },
  avisosLabel: { fontSize: 11, fontWeight: 700, color: COLORS.textSoft, marginBottom: 4, textTransform: "uppercase", letterSpacing: "0.3px" },
  avisosSelect: { width: "100%", border: `1px solid ${COLORS.border}`, borderRadius: 10, padding: "10px 8px", fontSize: 13, background: COLORS.bg, color: COLORS.text },
  avisosInput: { width: "100%", border: `1px solid ${COLORS.border}`, borderRadius: 10, padding: "10px 10px", fontSize: 13, background: COLORS.bg, color: COLORS.text, boxSizing: "border-box" },
  avisosTextarea: { width: "100%", border: `1px solid ${COLORS.border}`, borderRadius: 10, padding: "10px 12px", fontSize: 13, background: COLORS.bg, color: COLORS.text, resize: "none", fontFamily: "inherit", boxSizing: "border-box" },
  avisosSendButton: { padding: "12px", borderRadius: 10, border: "none", background: COLORS.primary, color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer", letterSpacing: "0.1px", boxShadow: "0 2px 6px rgba(20,63,53,0.24)" },
  avisosSentNote: { textAlign: "center", fontSize: 12, color: COLORS.primary, fontWeight: 600 },
  avisosSection: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "13px 14px", borderRadius: 12, border: `1px solid ${COLORS.border}`, background: COLORS.bg, cursor: "pointer", marginBottom: 10 },
  avisosSectionTitle: { display: "flex", alignItems: "center", fontSize: 14, fontWeight: 700 },
  avisosCount: { fontSize: 12, fontWeight: 700, color: COLORS.textSoft, background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 20, padding: "2px 9px" },
  feedbackList: { display: "flex", flexDirection: "column", gap: 8, marginTop: -2, marginBottom: 10 },
  feedbackCard: { border: `1px solid ${COLORS.border}`, borderRadius: 10, padding: "10px 12px", background: COLORS.surface },
  feedbackClient: { fontSize: 13, fontWeight: 700, display: "flex", alignItems: "center", gap: 6, marginBottom: 3 },
  sentDate: { fontSize: 11, color: COLORS.textSoft, marginBottom: 4 },
  unreadDot: { width: 6, height: 6, borderRadius: "50%", background: COLORS.extra },
  feedbackText: { fontSize: 12.5, color: COLORS.text, lineHeight: 1.4 },
  readMoreLink: { fontSize: 12, fontWeight: 700, color: COLORS.primary, background: "none", border: "none", cursor: "pointer", padding: 0 },
};

export { mobStyles };
