// Estilos da interface de gerência (desktop).
import { COLORS } from "./colors.js";

const styles = {
  page: { background: COLORS.bg, minHeight: "700px", display: "flex", justifyContent: "center", padding: "20px", fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif", color: COLORS.text },
  // Lote 4, 4.2 (achado da Marta): era `overflow: "hidden"` — isso faz
  // deste `shell` a "janela de rolagem" de referência para qualquer
  // `position: sticky` lá dentro (mesmo sem overflow real, por ser
  // "hidden"), e como ninguém rola o `shell` em si (quem cresce e rola é
  // a página), o Sidebar/AppSidebar sticky nunca prenderia à janela de
  // verdade. `overflow: "clip"` continua recortando visualmente os
  // cantos arredondados (mesmo efeito do `hidden` aqui, já que nada
  // dentro do shell hoje precisa de scroll programático), mas não cria
  // essa "janela de rolagem" — então o sticky escapa até ao `body`.
  shell: { width: "100%", maxWidth: 1200, minHeight: 680, background: COLORS.surface, borderRadius: 16, border: `1px solid ${COLORS.border}`, display: "flex", overflow: "clip" },
  sidebar: { width: 220, background: COLORS.sidebarBg, padding: "22px 18px", display: "flex", flexDirection: "column", borderRight: `1px solid ${COLORS.border}`, borderTop: `3px solid ${COLORS.extra}` },
  sidebarProductRow: { marginBottom: 18, background: COLORS.extraTint, borderRadius: 10, padding: "9px 12px" },
  brand: { display: "flex", alignItems: "center", gap: 10, marginBottom: 28, paddingBottom: 18, borderBottom: `1px solid ${COLORS.border}` },
  avatar: { width: 38, height: 38, borderRadius: "50%", background: COLORS.text, flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center", color: "#fff", fontSize: 14, fontWeight: 700, overflow: "hidden" },
  brandName: { fontSize: 14, fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: 140 },
  brandEmail: { fontSize: 10, color: COLORS.textSoft, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: 140 },
  menuList: { display: "flex", flexDirection: "column", gap: 4, flex: 1 },
  menuItem: { display: "flex", alignItems: "center", gap: 10, padding: "8px 10px", borderRadius: 9, fontSize: 13, fontWeight: 500, color: COLORS.textSoft, cursor: "pointer", border: "none", background: "transparent", width: "100%", textAlign: "left" },
  menuItemActive: { background: COLORS.surface, color: COLORS.primaryDark, fontWeight: 700, border: `1px solid ${COLORS.border}`, boxShadow: "0 1px 2px rgba(20,63,53,0.06)" },
  menuIconWrap: { width: 25, height: 25, borderRadius: 7, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, background: COLORS.extraTint, color: COLORS.extra },
  menuIconWrapActive: { background: COLORS.primaryTint, color: COLORS.primaryDark },
  sairRow: { fontSize: 12, color: COLORS.textSoft, textDecoration: "underline", cursor: "pointer", marginTop: 20, background: "none", border: "none", textAlign: "left" },

  content: { flex: 1, padding: "22px 28px", overflowY: "auto" },
  // `topBar`/`todayLabel` eram só do `TopBar` (views/shared/Layout.jsx),
  // removido na limpeza pós-Etapa 4 — removidos junto por ficarem órfãos.
  langButton: { display: "flex", alignItems: "center", background: COLORS.bg, border: `1px solid ${COLORS.border}`, borderRadius: 8, padding: "6px 10px", fontSize: 13, fontWeight: 500, color: COLORS.text, cursor: "pointer" },
  langMenu: { position: "absolute", right: 0, top: 34, background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 10, overflow: "hidden", zIndex: 20, minWidth: 120 },
  langMenuItem: { display: "block", width: "100%", textAlign: "left", padding: "9px 12px", fontSize: 13, border: "none", background: "transparent", cursor: "pointer", color: COLORS.text },

  toolbar: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, marginBottom: 16 },
  // `searchWrap`/`searchInput` (versão PC) ficaram órfãos depois que os
  // ecrãs da gerência passaram a usar o `SearchField`/`SearchSelect`
  // novos — removidos aqui, varredura de QA pós-Etapa 4. A versão mobile
  // equivalente (`mobStyles.searchWrap`/`searchInput`) continua em uso
  // num ecrã (EmployeeClientesScreen.jsx), por isso não foi tocada.
  newButton: { padding: "10px 16px", borderRadius: 10, border: "none", background: COLORS.primary, color: "#fff", fontSize: 13, fontWeight: 600, cursor: "pointer", letterSpacing: "0.1px", boxShadow: "0 1px 3px rgba(20,63,53,0.22)" },
  installAppButton: { display: "flex", alignItems: "center", justifyContent: "center", gap: 6, width: "100%", padding: "8px 0", background: "none", border: "none", color: COLORS.textSoft, fontSize: 12, fontWeight: 500, cursor: "pointer" },
  fieldError: { fontSize: 11, fontWeight: 600, color: COLORS.extra, marginTop: 4 },

  tableWrap: { border: `1px solid ${COLORS.border}`, borderRadius: 12, overflow: "hidden" },
  tableHeaderRow: { display: "flex", padding: "10px 16px", background: COLORS.bg, borderBottom: `1px solid ${COLORS.border}` },
  th: { fontSize: 11, fontWeight: 700, color: COLORS.textSoft, textTransform: "uppercase", letterSpacing: "0.3px" },
  tableRow: { width: "100%", display: "flex", alignItems: "center", padding: "13px 16px", background: COLORS.surface, border: "none", borderBottom: `1px solid ${COLORS.border}`, cursor: "pointer", textAlign: "left" },
  td: { fontSize: 13, color: COLORS.text, display: "flex", alignItems: "center", gap: 6 },
  statusBadge: { fontSize: 11, fontWeight: 700, borderRadius: 20, padding: "3px 10px", flexShrink: 0 },
  statusActive: { background: COLORS.successTint, color: COLORS.success },
  statusInactive: { background: COLORS.extraTint, color: COLORS.extra },
  noResults: { padding: "24px 16px", textAlign: "center", fontSize: 13, color: COLORS.textSoft },

  modalOverlay: { position: "fixed", inset: 0, background: "rgba(22, 33, 29, 0.45)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50, padding: 20 },
  modalCard: { background: COLORS.surface, borderRadius: 16, padding: 24, width: "100%", maxWidth: 620, maxHeight: "85vh", overflowY: "auto" },
  modalHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18 },
  modalTitle: { fontSize: 17, fontWeight: 700 },
  modalSubtitle: { fontSize: 12, color: COLORS.textSoft, marginTop: 2 },
  modalClose: { width: 28, height: 28, borderRadius: "50%", border: "none", background: COLORS.bg, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.textSoft, flexShrink: 0 },
  viewTitleRow: { display: "flex", alignItems: "center", gap: 12 },
  viewIconCircle: { width: 40, height: 40, borderRadius: "50%", background: COLORS.primaryTint, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  editButton: { display: "flex", alignItems: "center", padding: "8px 14px", borderRadius: 9, border: "none", background: COLORS.primary, color: "#fff", fontSize: 13, fontWeight: 600, cursor: "pointer", boxShadow: "0 1px 3px rgba(20,63,53,0.22)" },
  viewGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 18 },
  viewFieldLabel: { display: "flex", alignItems: "center", fontSize: 11, fontWeight: 700, color: COLORS.textSoft, marginBottom: 3, textTransform: "uppercase", letterSpacing: "0.3px" },
  viewFieldValue: { fontSize: 13.5, color: COLORS.text, lineHeight: 1.4 },

  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  fieldLabel: { fontSize: 11, fontWeight: 700, color: COLORS.textSoft, marginBottom: 4, textTransform: "uppercase", letterSpacing: "0.3px" },
  input: { width: "100%", border: `1px solid ${COLORS.border}`, borderRadius: 8, padding: "9px 10px", fontSize: 13, color: COLORS.text, background: COLORS.bg, boxSizing: "border-box" },
  textarea: { width: "100%", border: `1px solid ${COLORS.border}`, borderRadius: 8, padding: "9px 10px", fontSize: 13, color: COLORS.text, background: COLORS.bg, resize: "vertical", fontFamily: "inherit", boxSizing: "border-box" },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 20 },
  cancelButton: { padding: "10px 18px", borderRadius: 10, border: `1px solid ${COLORS.border}`, background: COLORS.surface, fontSize: 13, fontWeight: 600, cursor: "pointer", color: COLORS.text },
  saveButton: { padding: "10px 18px", borderRadius: 10, border: "none", background: COLORS.primary, color: "#fff", fontSize: 13, fontWeight: 600, cursor: "pointer", letterSpacing: "0.1px", boxShadow: "0 1px 3px rgba(20,63,53,0.22)" },

  sectionTitle: { fontSize: 13, fontWeight: 700, color: COLORS.primaryDark, marginBottom: 14, textTransform: "uppercase", letterSpacing: "0.4px" },
  title: { fontFamily: "'Poppins', sans-serif", fontSize: 23, fontWeight: 600, margin: "4px 0 20px", letterSpacing: "0.1px" },
  periodNav: { display: "flex", alignItems: "center", gap: 10 },
  navButton: { width: 26, height: 26, borderRadius: 7, border: `1px solid ${COLORS.border}`, background: COLORS.bg, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.extra },
  periodLabel: { fontSize: 15, fontWeight: 700, minWidth: 150, textAlign: "center" },

  /* login */
  loginShell: { width: "100%", maxWidth: 900, minHeight: 520, background: COLORS.surface, borderRadius: 16, border: `1px solid ${COLORS.border}`, display: "flex", overflow: "hidden" },
  loginLeft: { flex: 1, background: COLORS.primaryDark, position: "relative", overflow: "hidden", display: "flex", flexDirection: "column", justifyContent: "flex-end", padding: "40px 40px 36px" },
  loginLeftContent: { position: "relative", zIndex: 1, display: "flex", flexDirection: "column", gap: 14 },
  loginTagline: { fontSize: 15.5, fontWeight: 500, color: "#FFFFFF", lineHeight: 1.5, maxWidth: "30ch" },
  loginLeftFoot: { position: "relative", zIndex: 1, marginTop: 28, fontSize: 11, color: COLORS.primaryTint, letterSpacing: "0.5px", textTransform: "uppercase", fontFamily: "'Inter', sans-serif", fontWeight: 600 },
  loginRight: { flex: 1, padding: "40px 48px", display: "flex", flexDirection: "column" },
  loginFields: { display: "flex", flexDirection: "column", gap: 12, marginTop: "auto", marginBottom: "auto" },
  loginCompanyName: { fontFamily: "'Poppins', sans-serif", fontSize: 20, fontWeight: 600, marginBottom: 10, color: COLORS.text },
  loginInput: { border: `1px solid ${COLORS.border}`, borderRadius: 10, padding: "13px 14px", fontSize: 14, background: COLORS.bg, color: COLORS.text },
  forgotRow: { display: "flex", justifyContent: "flex-end" },
  forgotLink: { fontSize: 12, color: COLORS.textSoft, textDecoration: "underline", cursor: "pointer", background: "none", border: "none" },
  enterButton: { marginTop: 14, padding: "13px", borderRadius: 10, border: "none", background: COLORS.primary, color: "#fff", fontSize: 15, fontWeight: 600, cursor: "pointer", letterSpacing: "0.2px", boxShadow: "0 2px 6px rgba(20,63,53,0.28)" },

  /* dashboard */
  kpiRow: { display: "flex", gap: 16, marginBottom: 20 },
  kpiCard: { flex: 1, border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: "16px 18px", background: COLORS.bg, boxShadow: "0 1px 2px rgba(20,63,53,0.05)" },
  kpiTopRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 10 },
  kpiIconBadge: { width: 34, height: 34, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  kpiLabel: { fontSize: 12, fontWeight: 600, color: COLORS.textSoft, marginBottom: 8 },
  kpiValue: { fontSize: 28, fontWeight: 700, color: COLORS.primaryDark },
  midRow: { display: "flex", gap: 16, marginBottom: 20 },
  dashPendingCard: { flex: 1.4, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: "16px 18px" },
  dashPendingRow: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 2px", background: "transparent", border: "none", cursor: "pointer", textAlign: "left" },
  dashPendingLabel: { fontSize: 13, color: COLORS.text },
  dashPendingRight: { display: "flex", alignItems: "center", gap: 8 },
  dashPendingCount: { fontSize: 12, fontWeight: 700, color: COLORS.primaryDark, background: COLORS.primaryTint, borderRadius: 20, padding: "2px 9px", minWidth: 20, textAlign: "center" },
  gaugeCard: { flex: 1, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: "16px 18px", display: "flex", flexDirection: "column", alignItems: "center" },
  gaugeLegend: { display: "flex", gap: 24, marginTop: 4 },
  gaugeLegendItem: { textAlign: "center" },
  gaugeLegendLabel: { fontSize: 10, color: COLORS.textSoft, marginBottom: 2 },
  gaugeLegendValue: { fontSize: 16, fontWeight: 700, color: COLORS.text },
  historyRow: { display: "flex", gap: 16 },
  historyCard: { flex: 1, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: "16px 18px" },
  chartTitle: { fontSize: 12, fontWeight: 700, color: COLORS.textSoft, marginBottom: 8, textAlign: "center" },

  /* historico - dashboard mensal */
  histBackRow: { display: "flex", alignItems: "center", gap: 10, marginBottom: 4 },
  histBackButton: { display: "flex", alignItems: "center", gap: 6, padding: "7px 12px", borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.surface, fontSize: 12.5, fontWeight: 600, color: COLORS.text, cursor: "pointer" },
  histPeriodHeaderRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18, gap: 12 },
  histKpiDelta: { display: "inline-flex", alignItems: "center", gap: 3, fontSize: 11, fontWeight: 700, borderRadius: 20, padding: "2px 8px", marginTop: 8 },
  histKpiDeltaUp: { background: COLORS.successTint, color: COLORS.success },
  histKpiDeltaDown: { background: COLORS.extraTint, color: COLORS.extra },
  histKpiDeltaFlat: { background: COLORS.bg, color: COLORS.textSoft },

  /* clientes / funcionarios view */
  profileFieldsBlock: { paddingTop: 14, borderTop: `1px solid ${COLORS.border}` },
  clientChipsRow: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 8 },
  clientChip: { fontSize: 12, fontWeight: 600, color: COLORS.primaryDark, background: COLORS.primaryTint, borderRadius: 20, padding: "4px 12px" },
  noClientsText: { fontSize: 12.5, color: COLORS.textSoft, marginBottom: 8, fontStyle: "italic" },
  assignedNote: { fontSize: 11.5, color: COLORS.textSoft, lineHeight: 1.4 },

  /* agendas grid */
  agdSearchWrap: { marginBottom: 12, maxWidth: 260 },
  agdGridWrap: { border: `1px solid ${COLORS.border}`, borderRadius: 12, overflow: "hidden" },
  agdGridScroll: { overflowX: "auto" },
  agdGridRow: { display: "flex", borderBottom: `1px solid ${COLORS.border}` },
  agdGridHeaderRow: { background: COLORS.bg },
  agdStaffHeaderCell: { width: 140, minWidth: 140, padding: "10px 12px", fontSize: 11, fontWeight: 700, color: COLORS.textSoft, textTransform: "uppercase", letterSpacing: "0.3px", borderRight: `1px solid ${COLORS.border}` },
  agdDayHeaderCell: { width: 150, minWidth: 150, padding: "10px 8px", fontSize: 11, fontWeight: 700, color: COLORS.textSoft, textAlign: "center", borderRight: `1px solid ${COLORS.border}` },
  agdStaffCell: { width: 140, minWidth: 140, padding: "10px 12px", fontSize: 13, fontWeight: 600, color: COLORS.text, borderRight: `1px solid ${COLORS.border}`, display: "flex", alignItems: "center" },
  agdDayCell: { width: 150, minWidth: 150, padding: "8px", borderRight: `1px solid ${COLORS.border}`, display: "flex", flexDirection: "column", gap: 5, position: "relative" },
  agdChip: { display: "flex", alignItems: "center", gap: 4, background: COLORS.primaryTint, borderRadius: 6, padding: "4px 6px", fontSize: 11 },
  agdChipText: { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", color: COLORS.primaryDark, fontWeight: 600 },
  agdTeamBadge: { display: "flex", alignItems: "center", fontSize: 10, fontWeight: 700, color: COLORS.extra, flexShrink: 0 },
  agdChipRemove: { border: "none", background: "transparent", cursor: "pointer", color: COLORS.textSoft, display: "flex", flexShrink: 0 },
  agdAddCellButton: { border: `1px dashed ${COLORS.border}`, background: "transparent", borderRadius: 6, padding: "4px", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.textSoft },
  agdCellPopover: { position: "absolute", top: 4, left: 4, right: 4, background: COLORS.surface, border: `1px solid ${COLORS.primary}`, borderRadius: 8, padding: 6, zIndex: 10, boxShadow: "0 4px 12px rgba(0,0,0,0.12)" },
  agdCellSearchInput: { width: "100%", border: `1px solid ${COLORS.border}`, borderRadius: 6, padding: "5px 7px", fontSize: 11, marginBottom: 4, boxSizing: "border-box" },
  agdCellResults: { maxHeight: 110, overflowY: "auto" },
  agdCellResultRow: { display: "block", width: "100%", textAlign: "left", padding: "5px 6px", fontSize: 11, border: "none", background: "transparent", cursor: "pointer", borderRadius: 4, color: COLORS.text },
  agdCellCancel: { position: "absolute", top: 4, right: 4, border: "none", background: "transparent", cursor: "pointer", color: COLORS.textSoft },
  agdFootNote: { fontSize: 11, color: COLORS.textSoft, marginTop: 12, lineHeight: 1.5 },

  /* horas */
  horTop: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 },
  horSearchKpiRow: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, marginBottom: 16 },
  horSearchWrap: { flex: 1, maxWidth: 320 },
  horKpiBox: { display: "flex", gap: 26, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: "10px 22px" },
  horKpiBoxItem: { textAlign: "center" },
  horKpiBoxLabel: { fontSize: 11, color: COLORS.textSoft, marginBottom: 2 },
  horKpiBoxValue: { fontSize: 18, fontWeight: 700, color: COLORS.text },
  horStatusDone: { background: COLORS.successTint, color: COLORS.success },
  horStatusPending: { background: COLORS.extraTint, color: COLORS.extra },
  horStatusPaid: { background: COLORS.primaryTint, color: COLORS.primaryDark },
  horPendingExtraDot: { width: 7, height: 7, borderRadius: "50%", background: COLORS.extra, display: "inline-block" },
  horPaidToggle: { width: 20, height: 20, borderRadius: "50%", border: "2px solid", padding: 0 },
  horModalPaidToggle: { display: "flex", alignItems: "center", border: "2px solid", borderRadius: 20, padding: "6px 12px", fontSize: 12.5, fontWeight: 700, background: "transparent" },
  horPeriodTotal: { fontSize: 18, fontWeight: 700, color: COLORS.primaryDark, background: COLORS.primaryTint, borderRadius: 8, padding: "6px 14px" },
  horReportTable: { border: `1px solid ${COLORS.border}`, borderRadius: 10, overflow: "hidden" },
  horReportHeaderRow: { display: "flex", padding: "9px 14px", background: COLORS.bg, borderBottom: `1px solid ${COLORS.border}` },
  horRth: { fontSize: 10.5, fontWeight: 700, color: COLORS.textSoft, textTransform: "uppercase", letterSpacing: "0.3px" },
  horReportRow: { display: "flex", alignItems: "center", padding: "10px 14px", borderBottom: `1px solid ${COLORS.border}` },
  horRtd: { fontSize: 12.5, color: COLORS.text },
  horEditRowButton: { width: 24, height: 24, borderRadius: 6, border: `1px solid ${COLORS.border}`, background: COLORS.surface, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.extra, flexShrink: 0 },
  horVoidRowButton: { width: 24, height: 24, borderRadius: 6, border: `1px solid ${COLORS.border}`, background: COLORS.surface, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.extra, flexShrink: 0 },
  horVoidedTag: { display: "flex", alignItems: "center", fontSize: 11.5, fontWeight: 700, color: COLORS.extra },
  horApproveButton: { padding: "5px 12px", borderRadius: 7, border: "none", background: COLORS.primary, color: "#fff", fontSize: 11.5, fontWeight: 600, cursor: "pointer" },
  horApprovedTag: { display: "flex", alignItems: "center", fontSize: 11.5, fontWeight: 700, color: COLORS.success },
  horUndoButton: { width: 18, height: 18, borderRadius: "50%", border: "none", background: "rgba(31,111,92,0.12)", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: COLORS.primaryDark, marginLeft: 6 },
  horRowEditInput: { width: "100%", border: `1px solid ${COLORS.primary}`, borderRadius: 6, padding: "5px 7px", fontSize: 12.5, color: COLORS.text, boxSizing: "border-box" },
  horCancelSmall: { padding: "5px 10px", borderRadius: 7, border: `1px solid ${COLORS.border}`, background: COLORS.surface, fontSize: 11.5, fontWeight: 600, cursor: "pointer", color: COLORS.textSoft },
  horStepperRow: { display: "flex", alignItems: "center", justifyContent: "center", gap: 20, marginBottom: 8 },
  horModalQuestion: { fontSize: 13, color: COLORS.textSoft, marginBottom: 16 },
  horModalConfirmDanger: { flex: 1, padding: "11px", borderRadius: 10, border: "none", background: COLORS.extra, color: "#fff", fontSize: 14, fontWeight: 600, cursor: "pointer" },
  horLockedBanner: { marginTop: 14, display: "flex", gap: 10, alignItems: "flex-start", background: COLORS.primaryTint, border: `1px solid ${COLORS.primary}`, borderRadius: 12, padding: "12px 14px" },

  /* avisos */
  avFormCard: { border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: 18, marginBottom: 22 },
  avTypeToggleRow: { display: "flex", gap: 8, marginBottom: 14 },
  avTypeToggle: { display: "flex", alignItems: "center", padding: "7px 14px", borderRadius: 20, border: `1px solid ${COLORS.border}`, background: COLORS.bg, fontSize: 12.5, fontWeight: 600, color: COLORS.textSoft, cursor: "pointer" },
  avTypeActiveComplaint: { background: COLORS.extraTint, borderColor: COLORS.extra, color: COLORS.extra },
  avTypeActivePraise: { background: COLORS.successTint, borderColor: COLORS.success, color: COLORS.success },
  avTypeActiveNotice: { background: COLORS.primaryTint, borderColor: COLORS.primary, color: COLORS.primaryDark },
  avFormRow: { display: "flex", gap: 14 },
  avFormFooterRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 14 },
  avAttachButton: { display: "flex", alignItems: "center", padding: "8px 14px", borderRadius: 8, border: `1px dashed ${COLORS.border}`, background: "transparent", fontSize: 12.5, fontWeight: 600, color: COLORS.textSoft, cursor: "pointer" },
  avAttachActive: { borderColor: COLORS.primary, color: COLORS.primaryDark, background: COLORS.primaryTint, borderStyle: "solid" },
  avSentNote: { fontSize: 12, fontWeight: 700, color: COLORS.primary },
  avSendButtonSmall: { padding: "7px 14px", borderRadius: 8, border: "none", background: COLORS.primary, color: "#fff", fontSize: 12, fontWeight: 600, cursor: "pointer", marginTop: 8 },
  avSection: { width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", padding: "13px 16px", borderRadius: 12, border: `1px solid ${COLORS.border}`, background: COLORS.bg, cursor: "pointer", marginBottom: 10 },
  avSectionTitle: { display: "flex", alignItems: "center", fontSize: 14, fontWeight: 700 },
  avSectionCount: { fontSize: 12, fontWeight: 700, color: COLORS.textSoft, background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 20, padding: "2px 9px" },
  avItemsList: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 16 },
  avItemCard: { border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: "14px 16px" },
  avItemTopRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 },
  avItemTitle: { fontSize: 13.5, fontWeight: 700 },
  avItemDate: { fontSize: 11.5, color: COLORS.textSoft, marginTop: 2 },
  avItemText: { fontSize: 13, color: COLORS.text, lineHeight: 1.5 },
  avItemActions: { display: "flex", gap: 8, marginTop: 12 },
  avActionOutline: { padding: "7px 14px", borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.surface, fontSize: 12, fontWeight: 600, color: COLORS.text, cursor: "pointer" },
  avResponseBox: { marginTop: 10, paddingTop: 10, borderTop: `1px solid ${COLORS.border}` },
  avResponseLabel: { fontSize: 10.5, fontWeight: 700, color: COLORS.textSoft, marginBottom: 3, textTransform: "uppercase" },
  avNoItems: { fontSize: 13, color: COLORS.textSoft, textAlign: "center", padding: "16px 0" },

  /* definicoes */
  defSettingsCard: { border: `1px solid ${COLORS.border}`, borderRadius: 14, padding: "18px 20px", marginBottom: 16 },
  defSettingRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 20, padding: "10px 0" },
  defSettingLabel: { fontSize: 13.5, fontWeight: 600, color: COLORS.text },
  defSettingHint: { fontSize: 11.5, color: COLORS.textSoft, marginTop: 3, lineHeight: 1.4, maxWidth: 480 },
  defNumberInput: { width: 70, border: `1px solid ${COLORS.border}`, borderRadius: 8, padding: "8px 10px", fontSize: 13, color: COLORS.text, background: COLORS.bg, textAlign: "center" },
  defProfileRow: { display: "flex", gap: 24, alignItems: "flex-start" },
  defPhotoBlock: { display: "flex", flexDirection: "column", alignItems: "center", gap: 10, flexShrink: 0 },
  defPhotoCircle: { width: 76, height: 76, borderRadius: "50%", background: COLORS.primaryTint, display: "flex", alignItems: "center", justifyContent: "center", border: `2px solid ${COLORS.border}`, overflow: "hidden", position: "relative" },
  defPhotoImg: { width: "100%", height: "100%", objectFit: "cover" },
  defPhotoInitial: { fontSize: 26, fontWeight: 700, color: COLORS.primaryDark },
  defPhotoButton: { padding: "6px 12px", borderRadius: 8, border: "none", background: COLORS.primary, color: "#fff", fontSize: 11.5, fontWeight: 600, cursor: "pointer" },
  defPhotoButtonOutline: { padding: "6px 12px", borderRadius: 8, border: `1px solid ${COLORS.border}`, background: COLORS.surface, color: COLORS.textSoft, fontSize: 11.5, fontWeight: 600, cursor: "pointer" },
  defProfileFields: { flex: 1, display: "flex", flexDirection: "column", gap: 14 },
  defTextInput: { width: "100%", maxWidth: 340, border: `1px solid ${COLORS.border}`, borderRadius: 8, padding: "9px 10px", fontSize: 13, color: COLORS.text, background: COLORS.bg, boxSizing: "border-box" },
  defSaveRow: { display: "flex", justifyContent: "flex-end", alignItems: "center", gap: 14, marginTop: 8, marginBottom: 24 },
  defSavedNote: { display: "flex", alignItems: "center", fontSize: 12.5, fontWeight: 700, color: COLORS.primary },
};

export { styles };
